### ISSUE TITLE
[question]adaptive with slidershow

### ISSUE THREAD

**Issue by ghost** [briangonzalez/jquery.adaptive-backgrounds.js#86] opened 2018-11-26 10:37 UTC
slidershow,there are 
```
<ul>
<li></li>
<li></li>
<li></li>
<li></li>
</ul>
```
how to adaptive each background with different slidershow

**Comment by AlfredJKwack** [comment] 2018-12-01 23:15
Duplicate of #14

**Closed as completed by AlfredJKwack** 2018-12-01 23:15 UTC
